// <auto-generated />
using System;
using Elev8WebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elev8WebApp.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230901081217_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elev8WebApp.Models.EmployeeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DOE")
                        .HasColumnType("datetime2");

                    b.Property<string>("otherNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Elev8WebApp.Models.EmployeeSalaryInfo", b =>
                {
                    b.HasBaseType("Elev8WebApp.Models.EmployeeInfo");

                    b.Property<double>("deductions")
                        .HasColumnType("float");

                    b.Property<double>("salaryAmount")
                        .HasColumnType("float");

                    b.ToTable("EmployeeSalary");
                });

            modelBuilder.Entity("Elev8WebApp.Models.EmployeeSalaryInfo", b =>
                {
                    b.HasOne("Elev8WebApp.Models.EmployeeInfo", null)
                        .WithOne()
                        .HasForeignKey("Elev8WebApp.Models.EmployeeSalaryInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
